# Site settings
title: Genki Sugimoto's programming contest blog
email: genki.sugimoto.jp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I post anything related to programming contests I attended and problems I solved.
  Currently I like TopCoder, AOJ (Aizu Online Judge), and AtCoder.
baseurl: "/procon" # the subpath of your site, e.g. /blog/
url: "http://genkisugimoto.com" # the base hostname & protocol for your site
twitter_username: GenkiSugimoto
github_username:  Genki-S

# Build settings
markdown: kramdown
highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
